[workspace]

[package]
name = "rweb"
version = "0.1.1"
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/kdy1/rweb.git"
description = "Yet another web server framework for rust"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]


[dependencies]
rweb-macros = { path = "./macros" }
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"

[dev-dependencies]
bytes = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
http = "0.2"
hyper = "0.13"


[patch.crates-io]
warp = { git = "https://github.com/kdy1/warp.git" }